# Generated by Django 5.1.4 on 2026-03-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joueurs', '0002_alter_joueur_options_joueur_unique_numero_par_equipe'),
        ('matchs', '0007_alter_galerie_image_alter_galerie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('jaune', 'Jaune'), ('rouge', 'Rouge')], max_length=10)),
                ('minute', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_cartons', to='joueurs.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchs.match')),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('matchs_restants', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joueurs.joueur')),
            ],
        ),
    ]
