# Generated by Django 5.1.4 on 2026-03-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueurs', '0002_alter_joueur_options_joueur_unique_numero_par_equipe'),
        ('sanctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspension',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='joueurs.joueur'),
        ),
    ]
