# Generated by Django 5.1.4 on 2026-03-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0007_alter_galerie_image_alter_galerie_video'),
        ('sanctions', '0002_alter_suspension_joueur'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='match_declencheur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchs.match'),
        ),
    ]
