# Generated by Django 5.1.4 on 2026-03-06 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=100)),
                ('type_reclamation', models.CharField(choices=[('arbitrage', 'Arbitrage'), ('joueur', 'Joueur non qualifié'), ('organisation', 'Organisation'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='reclamations/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traitee', 'Traitée')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
