# Generated by Django 5.1.4 on 2026-03-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='interesse',
            new_name='auteur',
        ),
    ]
