# Generated by Django 5.1.4 on 2026-03-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
        ('reclamations', '0002_rename_interesse_reclamation_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipes.equipe'),
        ),
    ]
