# Generated by Django 5.1.4 on 2026-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_alter_reclamation_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='document_final',
            field=models.FileField(blank=True, null=True, upload_to='reclamations/final/'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
