# Generated by Django 6.0.5 on 2026-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_reclamation_decision_reclamation_document_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_cours', '🔄 En cours'), ('traitee', '✅ Traitée')], default='en_attente', max_length=20),
        ),
    ]
