# Generated by Django 6.0.5 on 2026-05-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
        ('reclamations', '0006_reclamation_vu_par_user_alter_reclamation_statut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='auteur',
            new_name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='vu_par_user',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='commentaire_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='decision_commission',
            field=models.CharField(blank=True, choices=[('accepte', 'Accepté'), ('rejete', 'Rejeté'), ('partiel', 'Accepté partiellement')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='document_final',
            field=models.FileField(blank=True, null=True, upload_to='decisions/'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipes.equipe'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='recours/'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='type_reclamation',
            field=models.CharField(choices=[('arbitrage', 'Mauvais arbitrage'), ('discipline', 'Problème disciplinaire'), ('joueur', 'Joueur non qualifié'), ('organisation', 'Organisation'), ('violence', 'Violence'), ('autre', 'Autre')], max_length=50),
        ),
    ]
