# Generated by Django 6.0.5 on 2026-05-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_rename_auteur_reclamation_utilisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamationcommentaire',
            old_name='auteur',
            new_name='utilisateur',
        ),
    ]
