# Generated by Django 5.1.4 on 2026-03-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('poste', models.CharField(choices=[('GK', 'Gardien'), ('DF', 'Défenseur'), ('MF', 'Milieu'), ('FW', 'Attaquant')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='joueurs/')),
                ('suspendu', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurs', to='equipes.equipe')),
            ],
        ),
    ]
