# Generated by Django 5.1.4 on 2026-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
        ('joueurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': ['equipe', 'numero']},
        ),
        migrations.AddConstraint(
            model_name='joueur',
            constraint=models.UniqueConstraint(fields=('numero', 'equipe'), name='unique_numero_par_equipe'),
        ),
    ]
