# Generated by Django 6.0.5 on 2026-05-15 18:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueurs', '0002_alter_joueur_options_joueur_unique_numero_par_equipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joueur',
            options={'ordering': ['equipe', 'numero'], 'verbose_name': 'Joueur', 'verbose_name_plural': 'Joueurs'},
        ),
        migrations.AddField(
            model_name='joueur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joueur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='numero',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
