# Generated by Django 6.0.4 on 2026-05-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
        ('joueurs', '0003_alter_joueur_options_joueur_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='A_VENIR', max_length=20)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe1', to='equipes.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe2', to='equipes.equipe')),
            ],
        ),
    ]
