# Generated by Django 6.0.5 on 2026-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueurs', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='statut',
            field=models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='A_VENIR', max_length=20),
        ),
    ]
