# Generated by Django 5.1.4 on 2026-03-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
        ('joueurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('priorite', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipes.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('joue', 'Joué')], default='programme', max_length=20)),
                ('stade', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs1', to='equipes.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs2', to='equipes.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('but', 'But'), ('carton_jaune', 'Carton jaune'), ('carton_rouge', 'Carton rouge'), ('suspension', 'Suspension')], max_length=30)),
                ('minute', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joueurs.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='matchs.match')),
            ],
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('jaune', 'Jaune'), ('rouge', 'Rouge')], max_length=10)),
                ('minute', models.PositiveIntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_cartons', to='joueurs.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='matchs.match')),
            ],
        ),
        migrations.CreateModel(
            name='But',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buts', to='joueurs.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buts', to='matchs.match')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('report', 'Match reporté'), ('buteur', 'Nouveau meilleur buteur'), ('fin_match', 'Match terminé')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipes.equipe')),
            ],
        ),
    ]
