# Generated by Django 5.1.4 on 2026-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotournoi',
            name='priorite',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('information', 'Information')], default='normal', max_length=20),
        ),
    ]
