# Generated by Django 5.1.4 on 2026-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0002_alter_infotournoi_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotournoi',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='infos/'),
        ),
        migrations.AlterField(
            model_name='infotournoi',
            name='priorite',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('information', 'Information')], default='information', max_length=20),
        ),
    ]
