# Generated by Django 5.1.4 on 2026-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0003_infotournoi_fichier_alter_infotournoi_priorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('report', 'Match reporté'), ('buteur', 'Nouveau meilleur buteur'), ('fin_match', 'Match terminé'), ('info', 'Information')], max_length=20),
        ),
    ]
