# Generated by Django 5.1.4 on 2026-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0004_alter_notification_type_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='galerie/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='galerie/videos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
