# Generated by Django 5.1.4 on 2026-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0005_galerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
