# Generated by Django 5.1.4 on 2026-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0006_galerie_archive_alter_galerie_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='galerie/photos/'),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='video',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='galerie/videos/'),
        ),
    ]
