# Generated by Django 5.1.4 on 2026-03-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('coach_principal', models.CharField(max_length=100)),
                ('coach_adjoint', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('buts_encaisses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('poste', models.CharField(max_length=50)),
                ('cartons_jaunes', models.IntegerField(default=0)),
                ('cartons_rouges', models.IntegerField(default=0)),
                ('suspendu', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joueurs', to='app_tournoi.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='A_VENIR', max_length=20)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe1', to='app_tournoi.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe2', to='app_tournoi.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('BUT', 'But'), ('CJ', 'Carton Jaune'), ('CR', 'Carton Rouge')], max_length=3)),
                ('minute', models.PositiveIntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='app_tournoi.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='app_tournoi.match')),
            ],
        ),
        migrations.CreateModel(
            name='But',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buts', to='app_tournoi.joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tournoi.match')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tournoi.equipe')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tournoi.match')),
            ],
        ),
    ]
